#!/bin/bash

pip install -r requirements.txt

mkdir -p ./.data

# Download the processed and augmented PCB datasets from Hugging Face.
python ./scripts/download_datasets.py

# download https://universe.roboflow.com/roboflow-100/printed-circuit-board/dataset/4
curl -L "https://universe.roboflow.com/ds/jczkaYRe50?key=h4Fau9lbj9" > ./.data/roboflow.zip; unzip ./.data/roboflow.zip -d ./.data/roboflow; rm ./.data/roboflow.zip

# download https://trust-hub.org/#/data/fics-pcb
mkdir -p ./.data/fics-pcb
curl -L https://trust-hub.org/downloads/resource/data/fics-pcb/README.md > ./.data/fics-pcb/README.md
curl -L https://trust-hub.org/downloads/resource/data/fics-pcb/s1.zip > ./.data/fics-pcb/s1.zip; unzip ./.data/fics-pcb/s1.zip -d ./.data/fics-pcb; rm ./.data/fics-pcb/s1.zip; mv ./.data/fics-pcb/s1/DSLR/img/s1_front.tif ./.data/fics-pcb/s1_front.tif; mv ./.data/fics-pcb/s1/DSLR/annotation/s1_front.csv ./.data/fics-pcb/s1_front.csv; rm -rf ./.data/fics-pcb/s1
curl -L https://trust-hub.org/downloads/resource/data/fics-pcb/s2.zip > ./.data/fics-pcb/s2.zip; unzip ./.data/fics-pcb/s2.zip -d ./.data/fics-pcb; rm ./.data/fics-pcb/s2.zip; mv ./.data/fics-pcb/s2/DSLR/img/s2_front.tif ./.data/fics-pcb/s2_front.tif; mv ./.data/fics-pcb/s2/DSLR/annotation/s2_front.csv ./.data/fics-pcb/s2_front.csv; rm -rf ./.data/fics-pcb/s2
curl -L https://trust-hub.org/downloads/resource/data/fics-pcb/s3.zip > ./.data/fics-pcb/s3.zip; unzip ./.data/fics-pcb/s3.zip -d ./.data/fics-pcb; rm ./.data/fics-pcb/s3.zip; mv ./.data/fics-pcb/s3/DSLR/img/s3_front.tif ./.data/fics-pcb/s3_front.tif; mv ./.data/fics-pcb/s3/DSLR/annotation/s3_front.csv ./.data/fics-pcb/s3_front.csv; rm -rf ./.data/fics-pcb/s3
curl -L https://trust-hub.org/downloads/resource/data/fics-pcb/s4.zip > ./.data/fics-pcb/s4.zip; unzip ./.data/fics-pcb/s4.zip -d ./.data/fics-pcb; rm ./.data/fics-pcb/s4.zip; mv ./.data/fics-pcb/s4/DSLR/img/s4_front.tif ./.data/fics-pcb/s4_front.tif; mv ./.data/fics-pcb/s4/DSLR/annotation/s4_front.csv ./.data/fics-pcb/s4_front.csv; rm -rf ./.data/fics-pcb/s4
curl -L https://trust-hub.org/downloads/resource/data/fics-pcb/s5.zip > ./.data/fics-pcb/s5.zip; unzip ./.data/fics-pcb/s5.zip -d ./.data/fics-pcb; rm ./.data/fics-pcb/s5.zip; mv ./.data/fics-pcb/s5/DSLR/img/s5_front.tif ./.data/fics-pcb/s5_front.tif; mv ./.data/fics-pcb/s5/DSLR/annotation/s5_front.csv ./.data/fics-pcb/s5_front.csv; rm -rf ./.data/fics-pcb/s5
curl -L https://trust-hub.org/downloads/resource/data/fics-pcb/s6.zip > ./.data/fics-pcb/s6.zip; unzip ./.data/fics-pcb/s6.zip -d ./.data/fics-pcb; rm ./.data/fics-pcb/s6.zip; mv ./.data/fics-pcb/s6/DSLR/img/s6_front.tif ./.data/fics-pcb/s6_front.tif; mv ./.data/fics-pcb/s6/DSLR/annotation/s6_front.csv ./.data/fics-pcb/s6_front.csv; rm -rf ./.data/fics-pcb/s6
curl -L https://trust-hub.org/downloads/resource/data/fics-pcb/s7.zip > ./.data/fics-pcb/s7.zip; unzip ./.data/fics-pcb/s7.zip -d ./.data/fics-pcb; rm ./.data/fics-pcb/s7.zip; mv ./.data/fics-pcb/s7/DSLR/img/s7_front.tif ./.data/fics-pcb/s7_front.tif; mv ./.data/fics-pcb/s7/DSLR/annotation/s7_front.csv ./.data/fics-pcb/s7_front.csv; rm -rf ./.data/fics-pcb/s7
curl -L https://trust-hub.org/downloads/resource/data/fics-pcb/s8.zip > ./.data/fics-pcb/s8.zip; unzip ./.data/fics-pcb/s8.zip -d ./.data/fics-pcb; rm ./.data/fics-pcb/s8.zip; mv ./.data/fics-pcb/s8/DSLR/img/s8_front.tif ./.data/fics-pcb/s8_front.tif; mv ./.data/fics-pcb/s8/DSLR/annotation/s8_front.csv ./.data/fics-pcb/s8_front.csv; rm -rf ./.data/fics-pcb/s8
curl -L https://trust-hub.org/downloads/resource/data/fics-pcb/s9.zip > ./.data/fics-pcb/s9.zip; unzip ./.data/fics-pcb/s9.zip -d ./.data/fics-pcb; rm ./.data/fics-pcb/s9.zip; mv ./.data/fics-pcb/s9/DSLR/img/s9_front.tif ./.data/fics-pcb/s9_front.tif; mv ./.data/fics-pcb/s9/DSLR/annotation/s9_front.csv ./.data/fics-pcb/s9_front.csv; rm -rf ./.data/fics-pcb/s9
curl -L https://trust-hub.org/downloads/resource/data/fics-pcb/s10.zip > ./.data/fics-pcb/s10.zip; unzip ./.data/fics-pcb/s10.zip -d ./.data/fics-pcb; rm ./.data/fics-pcb/s10.zip; mv ./.data/fics-pcb/s10/DSLR/img/s10_front.tif ./.data/fics-pcb/s10_front.tif; mv ./.data/fics-pcb/s10/DSLR/annotation/s10_front.csv ./.data/fics-pcb/s10_front.csv; rm -rf ./.data/fics-pcb/s10
curl -L https://trust-hub.org/downloads/resource/data/fics-pcb/s11.zip > ./.data/fics-pcb/s11.zip; unzip ./.data/fics-pcb/s11.zip -d ./.data/fics-pcb; rm ./.data/fics-pcb/s11.zip; mv ./.data/fics-pcb/s11/DSLR/img/s11_front1.tif ./.data/fics-pcb/s11_front.tif; mv ./.data/fics-pcb/s11/DSLR/annotation/s11_front1.csv ./.data/fics-pcb/s11_front.csv; rm -rf ./.data/fics-pcb/s11
curl -L https://trust-hub.org/downloads/resource/data/fics-pcb/s12.zip > ./.data/fics-pcb/s12.zip; unzip ./.data/fics-pcb/s12.zip -d ./.data/fics-pcb; rm ./.data/fics-pcb/s12.zip; mv ./.data/fics-pcb/s12/DSLR/img/s12_front.tif ./.data/fics-pcb/s12_front.tif; mv ./.data/fics-pcb/s12/DSLR/annotation/s12_front.csv ./.data/fics-pcb/s12_front.csv; rm -rf ./.data/fics-pcb/s12
# curl -L https://trust-hub.org/downloads/resource/data/fics-pcb/s13.zip > ./.data/fics-pcb/s13.zip; unzip ./.data/fics-pcb/s13.zip -d ./.data/fics-pcb; rm ./.data/fics-pcb/s13.zip; mv ./.data/fics-pcb/s13/DSLR/img/s13_front.tif ./.data/fics-pcb/s13_front.tif; mv ./.data/fics-pcb/s13/DSLR/annotation/s13_front.csv ./.data/fics-pcb/s13_front.csv; rm -rf ./.data/fics-pcb/s13
curl -L https://trust-hub.org/downloads/resource/data/fics-pcb/s14.zip > ./.data/fics-pcb/s14.zip; unzip ./.data/fics-pcb/s14.zip -d ./.data/fics-pcb; rm ./.data/fics-pcb/s14.zip; mv ./.data/fics-pcb/s14/DSLR/img/s14_front1.tif ./.data/fics-pcb/s14_front.tif; mv ./.data/fics-pcb/s14/DSLR/annotation/s14_front1.csv ./.data/fics-pcb/s14_front.csv; rm -rf ./.data/fics-pcb/s14
curl -L https://trust-hub.org/downloads/resource/data/fics-pcb/s15.zip > ./.data/fics-pcb/s15.zip; unzip ./.data/fics-pcb/s15.zip -d ./.data/fics-pcb; rm ./.data/fics-pcb/s15.zip; mv ./.data/fics-pcb/s15/DSLR/img/s15_front1.tif ./.data/fics-pcb/s15_front.tif; mv ./.data/fics-pcb/s15/DSLR/annotation/s15_front1.csv ./.data/fics-pcb/s15_front.csv; rm -rf ./.data/fics-pcb/s15
curl -L https://trust-hub.org/downloads/resource/data/fics-pcb/s16.zip > ./.data/fics-pcb/s16.zip; unzip ./.data/fics-pcb/s16.zip -d ./.data/fics-pcb; rm ./.data/fics-pcb/s16.zip; mv ./.data/fics-pcb/s16/DSLR/img/s16_front.tif ./.data/fics-pcb/s16_front.tif; mv ./.data/fics-pcb/s16/DSLR/annotation/s16_front.csv ./.data/fics-pcb/s16_front.csv; rm -rf ./.data/fics-pcb/s16
curl -L https://trust-hub.org/downloads/resource/data/fics-pcb/s17.zip > ./.data/fics-pcb/s17.zip; unzip ./.data/fics-pcb/s17.zip -d ./.data/fics-pcb; rm ./.data/fics-pcb/s17.zip; mv ./.data/fics-pcb/s17/DSLR/img/s17_front.tif ./.data/fics-pcb/s17_front.tif; mv ./.data/fics-pcb/s17/DSLR/annotation/s17_front.csv ./.data/fics-pcb/s17_front.csv; rm -rf ./.data/fics-pcb/s17
curl -L https://trust-hub.org/downloads/resource/data/fics-pcb/s18.zip > ./.data/fics-pcb/s18.zip; unzip ./.data/fics-pcb/s18.zip -d ./.data/fics-pcb; rm ./.data/fics-pcb/s18.zip; mv ./.data/fics-pcb/s18/DSLR/img/s18_front.tif ./.data/fics-pcb/s18_front.tif; mv ./.data/fics-pcb/s18/DSLR/annotation/s18_front.csv ./.data/fics-pcb/s18_front.csv; rm -rf ./.data/fics-pcb/s18
curl -L https://trust-hub.org/downloads/resource/data/fics-pcb/s19.zip > ./.data/fics-pcb/s19.zip; unzip ./.data/fics-pcb/s19.zip -d ./.data/fics-pcb; rm ./.data/fics-pcb/s19.zip; mv ./.data/fics-pcb/s19/DSLR/img/s19_front.tif ./.data/fics-pcb/s19_front.tif; mv ./.data/fics-pcb/s19/DSLR/annotation/s19_front.csv ./.data/fics-pcb/s19_front.csv; rm -rf ./.data/fics-pcb/s19
curl -L https://trust-hub.org/downloads/resource/data/fics-pcb/s20.zip > ./.data/fics-pcb/s20.zip; unzip ./.data/fics-pcb/s20.zip -d ./.data/fics-pcb; rm ./.data/fics-pcb/s20.zip; mv ./.data/fics-pcb/s20/DSLR/img/s20_front.tif ./.data/fics-pcb/s20_front.tif; mv ./.data/fics-pcb/s20/DSLR/annotation/s20_front.csv ./.data/fics-pcb/s20_front.csv; rm -rf ./.data/fics-pcb/s20
curl -L https://trust-hub.org/downloads/resource/data/fics-pcb/s21.zip > ./.data/fics-pcb/s21.zip; unzip ./.data/fics-pcb/s21.zip -d ./.data/fics-pcb; rm ./.data/fics-pcb/s21.zip; mv ./.data/fics-pcb/s21/DSLR/img/s21_front.tif ./.data/fics-pcb/s21_front.tif; mv ./.data/fics-pcb/s21/DSLR/annotation/s21_front.csv ./.data/fics-pcb/s21_front.csv; rm -rf ./.data/fics-pcb/s21
curl -L https://trust-hub.org/downloads/resource/data/fics-pcb/s22.zip > ./.data/fics-pcb/s22.zip; unzip ./.data/fics-pcb/s22.zip -d ./.data/fics-pcb; rm ./.data/fics-pcb/s22.zip; mv ./.data/fics-pcb/s22/DSLR/img/s22_front.tif ./.data/fics-pcb/s22_front.tif; mv ./.data/fics-pcb/s22/DSLR/annotation/s22_front.csv ./.data/fics-pcb/s22_front.csv; rm -rf ./.data/fics-pcb/s22
curl -L https://trust-hub.org/downloads/resource/data/fics-pcb/s23.zip > ./.data/fics-pcb/s23.zip; unzip ./.data/fics-pcb/s23.zip -d ./.data/fics-pcb; rm ./.data/fics-pcb/s23.zip; mv ./.data/fics-pcb/s23/DSLR/img/s23_front.tif ./.data/fics-pcb/s23_front.tif; mv ./.data/fics-pcb/s23/DSLR/annotation/s23_front.csv ./.data/fics-pcb/s23_front.csv; rm -rf ./.data/fics-pcb/s23
curl -L https://trust-hub.org/downloads/resource/data/fics-pcb/s24.zip > ./.data/fics-pcb/s24.zip; unzip ./.data/fics-pcb/s24.zip -d ./.data/fics-pcb; rm ./.data/fics-pcb/s24.zip; mv ./.data/fics-pcb/s24/DSLR/img/s24_front.tif ./.data/fics-pcb/s24_front.tif; mv ./.data/fics-pcb/s24/DSLR/annotation/s24_front.csv ./.data/fics-pcb/s24_front.csv; rm -rf ./.data/fics-pcb/s24
curl -L https://trust-hub.org/downloads/resource/data/fics-pcb/s25.zip > ./.data/fics-pcb/s25.zip; unzip ./.data/fics-pcb/s25.zip -d ./.data/fics-pcb; rm ./.data/fics-pcb/s25.zip; mv ./.data/fics-pcb/s25/DSLR/img/s25_front.tif ./.data/fics-pcb/s25_front.tif; mv ./.data/fics-pcb/s25/DSLR/annotation/s25_front.csv ./.data/fics-pcb/s25_front.csv; rm -rf ./.data/fics-pcb/s25
curl -L https://trust-hub.org/downloads/resource/data/fics-pcb/s26.zip > ./.data/fics-pcb/s26.zip; unzip ./.data/fics-pcb/s26.zip -d ./.data/fics-pcb; rm ./.data/fics-pcb/s26.zip; mv ./.data/fics-pcb/s26/DSLR/img/s26_front1.tif ./.data/fics-pcb/s26_front.tif; mv ./.data/fics-pcb/s26/DSLR/annotation/s26_front1.csv ./.data/fics-pcb/s26_front.csv; rm -rf ./.data/fics-pcb/s26
curl -L https://trust-hub.org/downloads/resource/data/fics-pcb/s27.zip > ./.data/fics-pcb/s27.zip; unzip ./.data/fics-pcb/s27.zip -d ./.data/fics-pcb; rm ./.data/fics-pcb/s27.zip; mv ./.data/fics-pcb/s27/DSLR/img/s27_front.tif ./.data/fics-pcb/s27_front.tif; mv ./.data/fics-pcb/s27/DSLR/annotation/s27_front.csv ./.data/fics-pcb/s27_front.csv; rm -rf ./.data/fics-pcb/s27
curl -L https://trust-hub.org/downloads/resource/data/fics-pcb/s28.zip > ./.data/fics-pcb/s28.zip; unzip ./.data/fics-pcb/s28.zip -d ./.data/fics-pcb; rm ./.data/fics-pcb/s28.zip; mv ./.data/fics-pcb/s28/DSLR/img/s28_front.tif ./.data/fics-pcb/s28_front.tif; mv ./.data/fics-pcb/s28/DSLR/annotation/s28_front.csv ./.data/fics-pcb/s28_front.csv; rm -rf ./.data/fics-pcb/s28
curl -L https://trust-hub.org/downloads/resource/data/fics-pcb/s29.zip > ./.data/fics-pcb/s29.zip; unzip ./.data/fics-pcb/s29.zip -d ./.data/fics-pcb; rm ./.data/fics-pcb/s29.zip; mv ./.data/fics-pcb/s29/DSLR/img/s29_front.tif ./.data/fics-pcb/s29_front.tif; mv ./.data/fics-pcb/s29/DSLR/annotation/s29_front.csv ./.data/fics-pcb/s29_front.csv; rm -rf ./.data/fics-pcb/s29
curl -L https://trust-hub.org/downloads/resource/data/fics-pcb/s30.zip > ./.data/fics-pcb/s30.zip; unzip ./.data/fics-pcb/s30.zip -d ./.data/fics-pcb; rm ./.data/fics-pcb/s30.zip; mv ./.data/fics-pcb/s30/DSLR/img/s30_front.tif ./.data/fics-pcb/s30_front.tif; mv ./.data/fics-pcb/s30/DSLR/annotation/s30_front.csv ./.data/fics-pcb/s30_front.csv; rm -rf ./.data/fics-pcb/s30
curl -L https://trust-hub.org/downloads/resource/data/fics-pcb/s31.zip > ./.data/fics-pcb/s31.zip; unzip ./.data/fics-pcb/s31.zip -d ./.data/fics-pcb; rm ./.data/fics-pcb/s31.zip; mv ./.data/fics-pcb/s31/DSLR/img/s31_front.tif ./.data/fics-pcb/s31_front.tif; mv ./.data/fics-pcb/s31/DSLR/annotation/s31_front.csv ./.data/fics-pcb/s31_front.csv; rm -rf ./.data/fics-pcb/s31

# download https://www.kaggle.com/datasets/frettapper/micropcb-images/data
curl -L https://www.kaggle.com/api/v1/datasets/download/frettapper/micropcb-images > ./.data/micropcb-images.zip; unzip ./.data/micropcb-images.zip -d ./.data/micropcb-images; rm ./.data/micropcb-images.zip

# download https://www.kaggle.com/datasets/benmalin/pcb-p-printed-circuit-boards-at-perspectives
curl -L https://www.kaggle.com/api/v1/datasets/download/benmalin/pcb-p-printed-circuit-boards-at-perspectives > ./.data/pcb-p.zip; unzip ./.data/pcb-p.zip -d ./.data/pcb-p; rm ./.data/pcb-p.zip

# download fcc photos from https://github.com/SanderGi/LCA, more can be downloaded using scripts/lookup_fcc_photos.py
cd ./.data
git clone https://github.com/SanderGi/LCA.git
cp -r ./LCA/data/vision_eval ./FCC
rm -rf ./LCA
cd ..
